[package]
name = "brusher"
version = "0.1.0"
edition = "2021"

[dependencies]
# truck-modeling = "0.5.1"
# truck-shapeops = "0.3.0"
# truck-meshalgo = "0.3.0"

[dev-dependencies]
bevy = "0.14.1"
bevy_panorbit_camera = "0.19.1"
